language: java
script:
  #Lance les tests
  - mvn clean verify --file ./simple-api/pom.xml

  #Connecte à Docker avec les variables d'env
  #enregistrées au préalable sur Travis
  - docker login -u $user -p $password

  #Build
  - docker build -t $user/mylittleproject:database database
  - docker build -t $user/mylittleproject:httpd httpd
  - docker build -t $user/mylittleproject:simple-api simple-api

  #Ajoute nom:version
#  - docker tag mylittleproject $user/mylittleproject:1.0

  #Push sur Docker hub
  - docker push $user/mylittleproject:database
  - docker push $user/mylittleproject:httpd
  - docker push $user/mylittleproject:simple-api

  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Chamalomg_Docker_TP2

addons:
  sonarcloud:
    organization: "chamalomg"
    token:
      secure: "$TOKEN_TRAVIS"
